import {
  mdiTrayArrowUp,
  mdiTagRemoveOutline,
  mdiMicrosoftExcel,
  mdiAccountMultipleOutline,
  mdiCartRemove,
  mdiEyeOutline,
  mdiCubeSend,
  mdiHandshakeOutline,
  mdiCubeOutline,
  mdiChevronDown,
  mdiChevronUp,
  mdiFileTableBoxMultipleOutline,
  mdiCloudOutline,
  mdiCurrencyUsd,
  mdiFolderCogOutline,
  mdiWrap,
  mdiAccount,
  mdiBellBadge,
  mdiCalendarMonth,
  mdiCart,
  mdiChevronRight,
  mdiClose,
  mdiCopyright,
  mdiFacebook,
  mdiHeart,
  mdiInstagram,
  mdiMagnify,
  mdiMenu,
  mdiPencil,
  mdiVolumeHigh,
  mdiVolumeOff,
  mdiWhatsapp,
  mdiFileDocumentEditOutline,
} from "@mdi/js";

export default {
  facebook: mdiFacebook,
  instagram: mdiInstagram,
  whatsapp: mdiWhatsapp,
  menu: mdiMenu,
  userAccount: mdiAccount,
  like: mdiHeart,
  cart: mdiCart,
  search: mdiMagnify,
  notification: mdiBellBadge,
  volumeOn: mdiVolumeHigh,
  volumeOff: mdiVolumeOff,
  calendar: mdiCalendarMonth,
  right: mdiChevronRight,
  copyright: mdiCopyright,
  close: mdiClose,
  edit: mdiPencil,
  dashboardMenu: mdiWrap,
  incomes: mdiCurrencyUsd,
  settings: mdiFolderCogOutline,
  edit: mdiFileDocumentEditOutline,
  inventory: mdiFileTableBoxMultipleOutline,
  cloud: mdiCloudOutline,
  arrowUp: mdiChevronUp,
  arrowDown: mdiChevronDown,
  orders: mdiCubeOutline,
  ordersInProcess: mdiCubeSend,
  ordersReceived: mdiHandshakeOutline,
  eye: mdiEyeOutline,
  forgottenCart: mdiCartRemove,
  team: mdiAccountMultipleOutline,
  excel: mdiMicrosoftExcel,
  newProduct: mdiTagRemoveOutline,
  upload: mdiTrayArrowUp
};
