import {
  mdiAccount,
  mdiBellBadge,
  mdiCalendarMonth,
  mdiCart,
  mdiChevronRight,
  mdiClose,
  mdiCopyright,
  mdiFacebook,
  mdiHeart,
  mdiInstagram,
  mdiMagnify,
  mdiMenu,
  mdiVolumeHigh,
  mdiVolumeOff,
  mdiWhatsapp,
} from "@mdi/js";

export default {
  facebook: mdiFacebook,
  instagram: mdiInstagram,
  whatsapp: mdiWhatsapp,
  menu: mdiMenu,
  userAccount: mdiAccount,
  like: mdiHeart,
  cart: mdiCart,
  search: mdiMagnify,
  notification: mdiBellBadge,
  volumeOn: mdiVolumeHigh,
  volumeOff: mdiVolumeOff,
  calendar: mdiCalendarMonth,
  right: mdiChevronRight,
  copyright: mdiCopyright,
  close: mdiClose
};
